{% set name = "cox" %}
{% set version = "0.1.post3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: baa6efce249e4f696de66df5939066f826cebe4b97379ebab8070cc15c9f812e

build:
  noarch: python
  number: 1
  entry_points:
    - cox-tensorboard=cox.tensorboard_view:main
  script: {{ PYTHON }} -m pip install .  -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - gitpython
    - grpcio
    - psutil
    - py3nvml
    - python >={{ python_min }}
    - tqdm
    - pandas
    - pytorch
    - dill
    - tensorboardx

test:
  requires:
    - python {{ python_min }}
  imports:
    - cox
  commands:
    - cox-tensorboard --help

about:
  home: https://github.com/MadryLab/cox
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: "Tools for Experiment Logging"
  doc_url: https://cox.readthedocs.io/en/latest/
  dev_url: https://github.com/MadryLab/cox

extra:
  recipe-maintainers:
    - oblute
    - rluria14
    - ndmaxar
